### ISSUE TITLE
Baro LPS22HBTR C94049

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#1]
can we fit on-board I2C baro LPS22HBTR | C94049

**Comment by rusefillc** [comment]
@mck1117 do we have software I2C or do we need hardware I2C?

**Comment by mck1117** [comment]
proteus uses bit bang (software) i2c and it works fine enough for baro, so any gpio will work.

**Comment by rusefillc** [comment]
@andreika-git please use non-I2C GPIO

**Comment by andreika-git** [comment]
Added the baro sensor:

![image](https://user-images.githubusercontent.com/15104768/197406568-6f4b6586-bc96-4e70-be7d-e2d54900e257.png)
![image](https://user-images.githubusercontent.com/15104768/197406575-bdce58ca-cd6c-49d2-81a3-735c3eff3ef4.png)
