### ISSUE TITLE
headers 3D

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#106]
3D seems to be missing ECU headers which are useful for case design

слева TE 6473423-1 https://www.te.com/usa-en/product-6473423-1.html
посередине 6437288-2
справа 6437288-3

![image](https://github.com/rusefi/alphax-8chan/assets/48498823/7d22ac85-008a-41aa-bd2e-bde26638cc32)

**Comment by rusefillc** [comment]
@Ringenium первый шаг - положить step в https://github.com/rusefi/kicad6-libraries?

**Comment by Ringenium** [comment]
@rusefillc добавил степы

**Comment by rusefillc** [comment]
@Ringenium вижу проресс библиотеки https://github.com/rusefi/kicad6-libraries/commit/db562ba9c1676e8cd117dd0bab22ead44a21c2a2

но ещё надо https://github.com/rusefi/alphax-8chan в самой плате как-то помочь? или прямо футпринт нужно связать с 3D?

**Comment by Ringenium** [comment]
@rusefillc понял, сегодня поправлю и на плате

**Comment by Ringenium** [comment]
![2023-06-03 132556](https://github.com/rusefi/alphax-8chan/assets/58686541/c9388686-9c42-49ee-a0cc-aab0ed3c6c9a)
подгрузил 3D файлы разъемов, но это не панацея и каждому пользователю нужно самому указывать путь к 3D файлу. Либо чтобы каждый раз так не делать, нужно в пути указывать переменные окружения и класть 3D модели в папку с кикадовскими моделями, типо вот так 
![Снимок экрана 2023-06-03 152506](https://github.com/rusefi/alphax-8chan/assets/58686541/57b3bd8e-80d7-4193-b927-be4c3f302bc6)

**Comment by rusefillc** [comment]
@Qwerty-OFF нужет твой совет

текущая проблема - 3D файлы скопированы

**Comment by Qwerty-OFF** [comment]
Кажется работает такая схема:
- библиотека компонентов лежит субмодулем в папке проекта
- в библиотеке компонентов хранятся 3д модели
- в посадочном месте пусть прописан относительно
![image](https://github.com/rusefi/alphax-8chan/assets/4116383/610314d9-bffd-463d-bbd4-3b17cab4b304)

Я [обновил](https://github.com/rusefi/kicad6-libraries/commit/a94ebd3fa1f0d04625b9a04affa1ee210521cff5) библиотеку, проверьте меня

**Comment by Ringenium** [comment]
@Qwerty-OFF У меня что-то не сработало( 
![image](https://github.com/rusefi/alphax-8chan/assets/58686541/9bab2679-3adc-4e96-8202-5d46eca6263a)

**Comment by Qwerty-OFF** [comment]
@Ringenium надо было футпринты обновить в плате, чтобы изменения появились, делал? Я могу вечером сделать если нужно

**Comment by Qwerty-OFF** [comment]
Возможно придется обновить кикад, потому что у меня свежий
Проект теперь выглядит вот так:
![image](https://github.com/rusefi/alphax-8chan/assets/4116383/29cbfe34-7b5f-4e23-a613-c36aa3486004)
При этом в самом компоненте путь к модели относительный как на моей картинке выше.
@Ringenium убедись что у тебя теперь модельки тоже работают

**Comment by Ringenium** [comment]
@Qwerty-OFF  а какая версия у тебя, 6?

**Comment by Qwerty-OFF** [comment]
7

**Comment by Ringenium** [comment]
@Qwerty-OFF Так можно в 7 работать, проблем с переносимостью проектов не будет?

**Comment by Qwerty-OFF** [comment]
@Ringenium переезжать в 7 можно, просто потом в 6 эти проекты не откроются

**Comment by Qwerty-OFF** [comment]
Кажется это можно закрыть
