### ISSUE TITLE
HW shortage: VR discrete analog output

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#116]
@Qwerty-OFF what exactly are we short on?

**Comment by rusefillc** [comment]
Worst case we go all MAX992x

**Comment by Qwerty-OFF** [comment]
We are missing:
3x ADC for VR analog output
3x PWM for VR threshold setup

**Comment by rusefillc** [comment]
At least one ADC would be nice, reminder those are ADC3 pins

**Comment by Qwerty-OFF** [comment]
MM176
