### ISSUE TITLE
MAP/MAF & PPS1/PPS2 clarification

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#12]
We have

![image](https://user-images.githubusercontent.com/48498823/192162011-62fe5615-b179-4e5a-bad3-2d4bf2203868.png)

Where are MAP/MAF & PPS1/PPS2?

**Comment by ElDominio** [comment]
None of them are dedicated? All can be used tofr those functions

**Comment by rusefillc** [comment]
@ElDominio question about your exact ford motor

**Comment by rusefillc** [comment]
At the moment we can only do 80% of thunder. We need to make sure our 80% fits your harness

**Comment by andreika-git** [comment]
Currently the following pinout is used:
- PPS1 = pin A33
- PPS2 = pin A14
- MAP1 = pin A22
- MAP2 is used for internal MAP sensor

![зображення](https://user-images.githubusercontent.com/15104768/193703050-8c438815-f107-4681-b5b3-7633a641e3c7.png)

**Comment by rusefillc** [comment]
@ElDominio confirm that you plan to repin current harness since we have no data on existing harness

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/197077806-d4624b1c-c9bc-4f2c-a77b-6955528d9816.png)
 APS = PPS
 
 
![image](https://user-images.githubusercontent.com/5685108/197077828-e67dd30f-7516-454c-abb8-dc2b8d61f412.png)

DI just in case

**Comment by andreika-git** [comment]
MAP1 is now on A22
PPS1 = A17
PPS2 = C31
