### ISSUE TITLE
Add additional CANBUS with internal 2pin connector

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-8chan#125]
I think having dual CAN might prove useful in some cases. Adding a 2 pin connector internally would not change pinout and give us that CAN

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/alphax-8chan/assets/48498823/f9ecf0ae-8b0a-453d-9eb9-f9dee584c04d)

https://rusefi.com/docs/pinouts/hellen/alphax-8chan/?pin=24C
