### ISSUE TITLE
VND7 not VND14NV04-E

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#15]
@ElDominio please approve VND7 for aux low side outputs to stay real and to get JLC assembly

**Comment by ElDominio** [comment]
Only for low side correct? Injectors still VND14? if so that's fine

**Comment by rusefillc** [comment]
See also #18

**Comment by rusefillc** [comment]
@ElDominio I need help understanding why do we need VND14 for injectors?

Actually the plan was to use SOT223 injector drivers like ZXMS6005SGTA for injectors same as hellen154hyundai or nissan

we would need to revisit if we have desire to support v10 i.e. if we need up to 10 injectors with same MOSFET

but first thing first: why VND14 for injectors?

**Comment by rusefillc** [comment]
@ElDominio was confused

got confirmation over phone no need for VND14 anywhere

**Comment by rusefillc** [comment]
For 8 injectors we will use the output module as usual

@andreika-git please fix schematics to say VND7 not VND14

**Comment by andreika-git** [comment]
![зображення](https://user-images.githubusercontent.com/15104768/194122553-50a04238-d667-4af1-90df-13af191b9841.png)
