### ISSUE TITLE
only one mux control line is needed

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#17]
@mck1117 please correct me if I am wrong

![image](https://user-images.githubusercontent.com/48498823/193357786-65991b42-d1fe-453e-b63e-976b6eae2000.png)

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/193405128-597cae33-bf26-423d-bc28-92fe49439f39.png)
![image](https://user-images.githubusercontent.com/15104768/193405138-52c12367-5398-4eef-8a1b-49ac604fc785.png)
