### ISSUE TITLE
Can there be two outputs that can also send 5V out? IGN9 IGN10 not rev A

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-8chan#18]
I'd like to have it be 10 channel-capable IF POSSIBLE, if this complicates things too much it's fine to not have it. I'm thinking in the next year or two a V10 might show up for one, but not sure. If it is too difficult we can make something else for that market later

**Comment by rusefillc** [comment]
@ElDominio please propose pin numbers

**Comment by ElDominio** [comment]
Are we still using Thunder pinout names? if so use 15-16?

**Comment by rusefillc** [comment]
Connector D pin 18
Connector D pin 19

**Comment by Qwerty-OFF** [comment]
@rusefillc время пришло?

**Comment by ElDominio** [comment]
These requests are old
