### ISSUE TITLE
sleep mode current consumption

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#19]
what can we do for proper low current sleep mode?

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/alphax-4chan/issues/65

**Comment by andreika-git** [comment]
1. Added a switchable 5V digital power supply:

![зображення](https://user-images.githubusercontent.com/15104768/194719779-89b78bf3-d144-4367-a285-0d52ab40df06.png)

2. Added a switchable 5V analog power supply (based on TLS115):

![зображення](https://user-images.githubusercontent.com/15104768/194719819-79647851-ed2b-43f8-ae99-14c1035eb750.png)

3. Changed some consumers to use switchable power:
- sd-card (3.3v)
- internal map sensor (5va)
- 2 knock modules (5va)
- 3 muxes (5va)
- 2 discrete-vr modules (5v)
- some leds (5v)

**Comment by rusefillc** [comment]
@andreika-git are you ready to apply label:"schematics: DONE"?

**Comment by rusefillc** [comment]
@Qwerty-OFF please review

**Comment by andreika-git** [comment]
Still need more tests... + Waiting for megamodule
