### ISSUE TITLE
no VVT2 trace feature or bug?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#21]
![image](https://user-images.githubusercontent.com/48498823/194120123-5efda404-b501-4ef5-9df2-07b457e1ca1b.png)

**Comment by andreika-git** [comment]
![зображення](https://user-images.githubusercontent.com/15104768/194406333-8417e464-2b88-4219-8720-6c0c292c73c5.png)

**Comment by rusefillc** [comment]
@andreika-git я нашёл её - она сидит над листом

![image](https://user-images.githubusercontent.com/48498823/197219038-42673ef1-8437-4158-8570-fc6f0c2a3331.png)

**Comment by andreika-git** [comment]
Removed the line, thanks!
