### ISSUE TITLE
What is IN_FLEX

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#22]
@ElDominio flex sensor input is it always digital or is it sometimes analog?

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/issues/155

**Comment by ElDominio** [comment]
Even though it is sometimes analog, if I read "IN_FLEX" I automatically assume it is a digital input. Anyone that wants to use an analog (puke) flex sensor should use a low speed Analog In

**Comment by rusefillc** [comment]
For 8chan Flex is digital only

**Comment by andreika-git** [comment]
This issue is dependent on https://github.com/andreika-git/hellen-one/issues/171
Currently we have no more free pins to move flex input anywhere.

**Comment by rusefillc** [comment]
Progress on https://github.com/andreika-git/hellen-one/issues/171 we have free pins now!

**Comment by andreika-git** [comment]
Moved IN_FLEX and CAM_HALL to separate digital input stages:

![image](https://user-images.githubusercontent.com/15104768/197406440-1847095c-0fb6-4ab3-8b20-0e3a67292b10.png)

Moved FLEX to another digital pin:

![image](https://user-images.githubusercontent.com/15104768/197406477-54415250-b8ca-47ac-bfb8-c2ebd7f135c7.png)

Which allowed to add two more analog inputs (muxed)!

![image](https://user-images.githubusercontent.com/15104768/197406506-366fa5b9-f946-4171-9cb5-0252322a5fcc.png)
![image](https://user-images.githubusercontent.com/15104768/197406535-80057eb8-c7bc-47ce-950a-20d2db38ac11.png)
