### ISSUE TITLE
That vr-discrete analog output shall we wire it

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#23]
@mck1117 any hints/tricks on where to route vr-discrete analog output? adc3 or normal ADC input? muxed or not muxed?

**Comment by mck1117** [comment]
adc3 non-muxed, same rules as knock input

**Comment by andreika-git** [comment]
Currently VR analog outputs already use ADC3 non-muxed inputs (ADC3_6 and ADC3_8):
![image](https://user-images.githubusercontent.com/15104768/197406287-7a9a7021-a371-49ac-abe1-d7b7528e96ae.png)
