### ISSUE TITLE
Schematics is DONE need review

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#24]
This https://github.com/rusefi/alphax-8chan is now SCHEMATICS DONE

**Comment by rusefillc** [comment]
@Qwerty-OFF can you please review?

@mck1117 can you please review?

**Comment by mck1117** [comment]
Add a 1n cap from the input and after the resistor to ground for the digital inputs. Better noise suppression.

Add here (and to others):

Add from `IN_CAM_HALL` and pin 3 to ground (same to all channels).

<img width="886" alt="image" src="https://user-images.githubusercontent.com/568254/197410628-fd49f087-e294-4bb7-992d-4463866b5b84.png">

Proteus for reference:

<img width="743" alt="image" src="https://user-images.githubusercontent.com/568254/197410610-b0b43c32-accd-4ff5-bc86-c57959632bef.png">

**Comment by mck1117** [comment]
Connect LED to processed input, not raw input for `IN_CAM_HALL` (others seem to already do this, but not cam??)

<img width="627" alt="image" src="https://user-images.githubusercontent.com/568254/197410749-5270572d-6102-4e61-85af-64b404fd966c.png">

**Comment by mck1117** [comment]
Inconsistent muxed analog naming:

It's confusing that some mux [AT1, AT3] -> `IAT`, but others mux to a net called `AN3_4`. The net should not be called `IAT`, because it isn't IAT.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/568254/197410797-1f854af2-bac6-47d1-812b-daec1e547f34.png">

**Comment by rusefillc** [comment]
@mck1117 let's create separate tickets like https://github.com/rusefi/alphax-8chan/issues/25?

**Comment by andreika-git** [comment]
#25, #28 and #29 done.

**Comment by rusefillc** [comment]
@mck1117 we now have PCB, could be 48 to placing the order

**Comment by rusefillc** [comment]
@mck1117 
@dron0gus 
@Qwerty-OFF 

Let's have the last round of review?
