### ISSUE TITLE
 digital inputs. Better noise suppression.

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#28]
See https://github.com/rusefi/alphax-8chan/issues/24#issuecomment-1288176713

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/197724597-c5c9f902-2efd-4902-a504-f7ae1da9358f.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF are we affected by same on nissan or hyundai?

**Comment by Qwerty-OFF** [comment]
@rusefillc Modules do not contain these capacitors

**Comment by rusefillc** [comment]
See https://github.com/rusefi/rusefi/pull/4656

**Comment by mck1117** [comment]
Long ago when I said "copy the proteus digital input stages", I did really mean _exactly copy them_. They're the most bulletproof ones we've used so far.
