### ISSUE TITLE
analog mux between IAT and CLT, where else?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#3]
https://github.com/rusefi/stim is finally a success shall we use same analog mux chip on 8chan for VBatt/CLT/IAT/something else?

actually let's use C91307 2 input/single control bit

IAT/CLT
AT3/AT4
VBAT/xxx?

**Comment by mck1117** [comment]
Use the same 2-input muxes as inside the VR-discrete module.

Usable on any channel other than MAP or knock.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/176197545-ba39dda3-5f74-46cc-a55c-22e841d72598.png)

C87403
NC7SB3157P6X $5 no way

@andreika-git did we substitute on alphax?

**Comment by mck1117** [comment]
there are plenty of cheap options like  C91307

https://jlcpcb.com/parts/componentSearch?isSecondLevel=true&name=Analog%20Switches%20%2F%20Multiplexers%20&firstName=Interface%20Ics

**Comment by rusefillc** [comment]
#17

**Comment by ElDominio** [comment]
I'd say choose some of the last pins in the pinout to be low priority Analog inputs, maybe have the first 10/12 high priority then the rest low priority?

**Comment by rusefillc** [comment]
@andreika-git let's mux one of the aux analog inputs with a 3rd single channel mux controller by same AMUX line

**Comment by rusefillc** [comment]
@andreika-git let's mux one of aux from #16

**Comment by andreika-git** [comment]
Done!
![зображення](https://user-images.githubusercontent.com/15104768/194052441-4777616d-cc41-4023-af2d-301e3fe517cb.png)
![зображення](https://user-images.githubusercontent.com/15104768/194052482-b9204583-d451-4ee1-a11a-18e864e5e231.png)

**Comment by rusefillc** [comment]
@mck1117 :)

**Comment by mck1117** [comment]
@andreika-git wait, is that mux BEFORE the analog input filtering stage? That WILL NOT work. It must be muxed as close to the MCU as possible. The analog input filters only have a few hundred hz of bandwidth, so switching between inputs at hundreds of hz will not work.

**Comment by mck1117** [comment]
> @mck1117 what's your level of confidence with single control line, multiple 2-input muxes implementation?

100% confident, but the mux does need to be in the correct spot for it to work.

**Comment by andreika-git** [comment]
Now mux is between filtered signals closer to mcu:
![зображення](https://user-images.githubusercontent.com/15104768/194406249-46f53e45-6843-47cc-b355-54f4d47ea8be.png)
