### ISSUE TITLE
0603-4 or x4 0402?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#30]
https://github.com/rusefi/alphax-4chan/issues/71 freaks me out regarding R0603-4 availability

also I hear those are not easy to hand-solder if repairs are needed

@andreika-git @mck1117 @Qwerty-OFF @dron0gus what are the pros and cons between 0603-4 array versus four single 0201 components?

**Comment by Qwerty-OFF** [comment]
0201 almost impossible to hand-solder. Four 0402 is the preferred option. Also, JLC seems to have a lot of C425239
![image](https://user-images.githubusercontent.com/4116383/198121228-e5e2d884-b89b-41e0-9c13-09d0f0e6dc85.png)

**Comment by mck1117** [comment]
yeah, please do not use 0201, I'm not even sure JLC will reliably mount those.

0402 is plenty reliable, proteus uses a million of em

**Comment by rusefillc** [comment]
It was a typo, I was thinking 4x0402

**Comment by rusefillc** [comment]
@Qwerty-OFF @mck1117 @andreika-git what about 0x4 0402?
