### ISSUE TITLE
ONBOARD_MAP double use?

### ISSUE THREAD

**Issue by andreika-git** [rusefi/alphax-8chan#33]
Currently we have two internal MAP sensors on the same analog line:

![image](https://user-images.githubusercontent.com/15104768/203626610-4dcc4373-08ca-41c1-ac6d-709f59913823.png)

One is BARO sensor (as in 4chan), and another one is double footprint MAP (MPX***).
Do we need both?

**Comment by rusefillc** [comment]
We definitely cannot afford two on-board analog MAP sensors

let's remove analog baro. One day later we might add on-board I2C baro but that would be a separate ticket

**Comment by rusefillc** [comment]
Now I am confused with the image

Which one is baro? is U3 baro? is U13 baro? what makes something baro?

See also #7

**Comment by andreika-git** [comment]
The Baro is U3. Removed, done.
https://github.com/rusefi/alphax-8chan/commit/6ec1681528d9ea567d7daeb456792b08ba04dfb6

**Comment by andreika-git** [comment]
The same as 2chan:
![image](https://user-images.githubusercontent.com/15104768/206923442-efadf53e-85a2-4ce0-9186-2e377f066e6c.png)
