### ISSUE TITLE
tle9201 not rendered on ibom [now not selectable by mouse cursor for some reason]

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#35]
![image](https://user-images.githubusercontent.com/48498823/204993552-1052096e-2644-4ded-bbc8-24feaff4c366.png)

**Comment by rusefillc** [comment]
Seems to still be an issue, is this easy or not?

battery seems to be another broken one, what is the level of effort?

**Comment by rusefillc** [comment]
@Qwerty-OFF says in relation to ANOTHER board, not sure if relevant or not

"названия у футпринта в хелленне и кикаде разные. Название футпринта в кикаде поменялось когда я в него железно прикрутил большие дырки для пайки"

**Comment by andreika-git** [comment]
The problem is in the definition of Infineon_PG-DSO-12-11.kicad_mod. It used a newer Kicad multiline format instead of older one-line format. I've updated the Hellen-One scripts to understand the new format.
