### ISSUE TITLE
VR only positive

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#39]
То что от VR на разъем уходят только положительные линии, а негативные заземлены так и задумано?

**Comment by andreika-git** [comment]
Насколько я знаю, на этом разъёме не предусмотрены отрицательные линии для VR-сенсоров, а вместо этого сенсор подключается вторым концом на аналоговую землю. На случай, если кому-нибудь понадобится изменить это, предусмотрены джамперы R112 и R113.
