### ISSUE TITLE
SD card and battery

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#4]
SD card requirment would mean we are waiting to test a real life https://github.com/rusefi/alphax-4chan/issues/40

**Comment by rusefillc** [comment]
4chan rev E has working SD

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/193405284-67ebddbd-ce55-4a1e-8e07-32b3be14e23b.png)
![image](https://user-images.githubusercontent.com/15104768/193405293-4d74bdf8-b1cb-443b-8c53-38054b0379f6.png)
