### ISSUE TITLE
Q5 high voltage

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#40]
Q5 не станет плохо если на IN_CRANK+ будет висеть VR-сенсор с гигантским напряжением?

**Comment by andreika-git** [comment]
Да, есть такая опасность... Есть ли идеи, как это улучшить?

**Comment by andreika-git** [comment]
Added protection diodes:
![зображення](https://user-images.githubusercontent.com/15104768/206590944-4189be79-5388-46ee-91c7-99bfd2dcc8fa.png)
