### ISSUE TITLE
TACH и MAIN LEDs

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#43]
Я не понимаю как будут гореть светодиоды TACH и MAIN если у них последовательно стоит 1N4148 в противоположном направлении. Может он должен смотреть туда же куда и светодиод, тогда за счет его большого обратного напряжения со светодиодом ничего не случится?

**Comment by andreika-git** [comment]
Done!
![зображення](https://user-images.githubusercontent.com/15104768/206566463-ba6c7eaf-4915-41f8-a3ab-1634ac8eecd1.png)
