### ISSUE TITLE
Yaml

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#45]
yaml progress in https://github.com/rusefi/rusefi/tree/master/firmware/config/boards/hellen/alphax-8chan/connectors folder is needed

https://rusefi.com/docs/pinouts/hellen/alphax-8chan/ would be the result

**Comment by andreika-git** [comment]
@rusefillc Do we use "normal" or "inverted" pin numbers? For example, is CAN2+ on pin D22 (as in the schematics) or D3 as in the current yaml file?

**Comment by rusefillc** [comment]
@andreika-git we keep 99% of copper/traves (unless changes due to fixes)

I do not remember if pinout was already flipped or not but we fix yaml and PDF to match copper gerber
