### ISSUE TITLE
VND10N06TR-E direct drive with stm32

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#49]
See https://github.com/andreika-git/hellen-one/issues/236

How is VND10 in this regard?

**Comment by rusefillc** [comment]
@Qwerty-OFF says VND10 has the similar curve

**Comment by mck1117** [comment]
exact PN?

**Comment by rusefillc** [comment]
@Qwerty-OFF stm32 is allowed to output 2.9v?

![WhatsApp Image 2022-12-13 at 16 17 40](https://user-images.githubusercontent.com/48498823/207445623-1b9a1fd1-2da6-4961-8b48-f872677a02b1.jpg)

**Comment by rusefillc** [comment]
> exact PN?

VND10N06TR-E

**Comment by mck1117** [comment]
I think VND10xxxx will require 5v drive.

> stm32 is allowed to output 2.9v?

You've read that slightly wrong, `vdd - 0.4` is for supply voltage to the stm32 between 2-2.7 volts. If you're sourcing 20mA with a supply voltage of 2.7-3.6v, it could be as low as `vdd - 1.3`, or in our case, 2.0 volts. BUT - that's when sourcing 20mA, which we aren't trying to do. With the current 4.7k pulldown, it's only 0.7mA, so you'll see very near the full 3.3v.

**Comment by Qwerty-OFF** [comment]
Fixed
https://github.com/rusefi/alphax-8chan/issues/52#issuecomment-1356315494
