### ISSUE TITLE
configurable high OR low side aux output, 5A

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#5]
Can we have a configurable high OR low side 5A output?

**Comment by rusefillc** [comment]
would TLE9201 be the best or at least one of the options for high-current configrable push-pull output?

**Comment by rusefillc** [comment]
@dron0gus says MC33879 but 0.6A

**Comment by Qwerty-OFF** [comment]
MC33887APVW

**Comment by rusefillc** [comment]
MC33887APVW looks great!

@dron0gus can you please double-check just to confirm that we can use MC33887APVW as two independent pull/push outputs?

**Comment by dron0gus** [comment]
@rusefillc 
It is possible to use MC33887APVW as two independent push/pull,
BUT it is not possible to independently switch one output to Hi-Z. Only both at the same time.
![Screenshot from 2022-08-08 11-33-21](https://user-images.githubusercontent.com/28624689/183375620-bfa262ba-f6b1-4b50-83f7-c943ed63dc9a.png)

**Comment by dron0gus** [comment]
TLE94112EL is cool. But almost out of stock.

**Comment by rusefillc** [comment]
@mck1117 what are your thoughts on MC33887APVW as most flexible push/pull chip?
