### ISSUE TITLE
VND7xxxxx need series resistor Rin

### ISSUE THREAD

**Issue by mck1117** [rusefi/alphax-8chan#52]
![image](https://user-images.githubusercontent.com/568254/207448408-0f983d20-c3a0-4bc2-a2de-20ecf48bf521.png)

ST requires minimum of 150 ohms, or overvoltage and latchup protection may not work:

![image](https://user-images.githubusercontent.com/568254/207448522-7498974a-d139-49d7-963d-11436b60a696.png)

**Comment by Qwerty-OFF** [comment]
IGN module contains a level converter and a series resistor.
![image](https://user-images.githubusercontent.com/4116383/208250033-964907f1-a2cf-4e6e-8ffc-8eaba6d04ea5.png)
