### ISSUE TITLE
Duplicated designators

### ISSUE THREAD

**Issue by Qwerty-OFF** [rusefi/alphax-8chan#53]
В проекте есть элементы с порядковым номером больше 100, обозначения дублируются с элементами внутри модулей. Нужно переименовать компоненты чтоб попали в неиспользуемый диапазон.

**Comment by rusefillc** [comment]
Ой, а скрипты не должны ли упасть?!

**Comment by Qwerty-OFF** [comment]
Было бы правильно, сейчас это видно у JLC вот так
![image](https://user-images.githubusercontent.com/4116383/207978324-3c0692e1-815f-47f4-aa26-87e44b3d3874.png)

**Comment by rusefillc** [comment]
hellen-one validation https://github.com/andreika-git/hellen-one/issues/244
