### ISSUE TITLE
plugs C and D pinout is mirrored

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#59]
A-B silk and PCB matches pin numbers on the plugs

![a-b-higher-numbers-at-edge](https://user-images.githubusercontent.com/48498823/211110709-6fdca707-0368-4d6a-8dda-3c164d8a837b.jpg)

C and D silk and PCB does not match numbers on the plugs

![c-d-lower-numbers-at-edge](https://user-images.githubusercontent.com/48498823/211110833-01b1c9ca-edeb-4d1f-b859-975de2b74db7.jpg)

**Comment by rusefillc** [comment]
issue is somewhere around https://github.com/rusefi/kicad6-libraries/issues/1 https://github.com/rusefi/alphax-8chan/issues/26 https://github.com/rusefi/alphax-8chan/issues/27

**Comment by andreika-git** [comment]
С & D:
kicad6-libraries/Connectors.pretty/6437288-2.kicad_mod 
kicad6-libraries/Connectors.pretty/6473423-1.kicad_mod

**Comment by rusefillc** [comment]
So A&B everything as rendered on https://rusefi.com/docs/pinouts/hellen/alphax-8chan/

AT THE MOMENT C&D is mirrored over center line in relation to https://rusefi.com/docs/pinouts/hellen/alphax-8chan/

pin 10 is pin 18
pin 18 is pin 10
pin 8 is pin 26
pin 26 is pin 8

**Comment by ElDominio** [comment]
I vote keep mirrored. Gives me peace of mind, and no need for redesign

**Comment by Qwerty-OFF** [comment]
@rusefillc что мне сейчас c этим делать?
