### ISSUE TITLE
rev A: test new compact VR

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#62]
@mck1117 @ElDominio looking for help with https://github.com/andreika-git/hellen-one/tree/master/modules/vr-discrete/0.2 testing

**Comment by ElDominio** [comment]
Question about VR, does CMP-/CKP- go to sensor ground? Or where?

**Comment by rusefillc** [comment]
> Question about VR, does CMP-/CKP- go to sensor ground? Or where?

Not unless you connect yourself?
