### ISSUE TITLE
How does VR work?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-8chan#68]
Example, Coyote engine has VR on crank and two cams (other cams are Hall), how do I wire it?

**Comment by rusefillc** [comment]
I believe it's only two VR on 8chan at the moment

![WhatsApp Image 2023-01-29 at 19 53 56](https://user-images.githubusercontent.com/48498823/215370362-ca4fbfbe-9fcf-4a12-883e-2161c180ac5d.jpg)

**Comment by ElDominio** [comment]
I need one more :(

**Comment by ElDominio** [comment]
Where do I wire VR-? @rusefillc

**Comment by rusefillc** [comment]
@ElDominio Analog Ground https://rusefi.com/docs/pinouts/hellen/alphax-8chan/?pin=24A

**Comment by ElDominio** [comment]
[8chanvrcoyote.zip](https://github.com/rusefi/alphax-8chan/files/11410621/8chanvrcoyote.zip)

Is this okay??
![image](https://user-images.githubusercontent.com/5685108/236583857-f949e4dc-4120-4a3b-adf5-d50ffec98aad.png)

It might not have worked because I am dumb
