### ISSUE TITLE
On-board MAP

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#7]
@eldominio if we fancy a fancy CNC metal case do you see 8chan having on-board MAP sensor or not really?

**Comment by ElDominio** [comment]
Yes please, most people need it since they don't know how to connect cables.

**Comment by rusefillc** [comment]
"Hex Bulkhead Straight Fitting 2PCS Hose Barb Bulkhead Hex Union Brass Barbed Fitting Connector with 1/4inch Flat Washers"

![image](https://user-images.githubusercontent.com/48498823/181880533-eb8cdf3a-bd2e-4e21-a0ed-adad820344f6.png)

**Comment by rusefillc** [comment]
@ElDominio where do you want to place the nipple? would you like the nipple between 60 and 60 or else?

**Comment by rusefillc** [comment]
@ElDominio what sensor do you prefer?

there is MPX5700AP which seems to be more suited for brass fitting and hose without turns inside the ECU

**Comment by rusefillc** [comment]
Status update:
@ElDominio uses something barbed on 4chan cases already! for now 8chan should use same exact map as 4chan and @ElDominio plans to use same exact barbed fitting and internal hose solution

**Comment by ElDominio** [comment]
https://www.ebay.com/itm/252780287663 This is the item i use, and a hose inside the case

**Comment by rusefillc** [comment]
let's have a triple-footprint:

to accomodate both sensors soldered directly to PCB (horizontal 2.5 bar and vertical 4bar)

and also a custom 0.1" strip for angled mount. I guess 0.1" strip could actually match 2.5bar pinout?

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/193405996-93acb588-bca1-477b-b8ee-34bc391ee305.png)
