### ISSUE TITLE
USB connectivity let's use USBBF7

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#8]
Let's use USBBF7 

See https://rusefi.com/forum/viewtopic.php?p=42648#p42648

**Comment by rusefillc** [comment]
Same 5 pin header as on https://github.com/rusefi/hellen154hyundai

**Comment by andreika-git** [comment]
![зображення](https://user-images.githubusercontent.com/15104768/194641451-1087386d-33f3-4ae4-bc9b-6110e751a1db.png)
