### ISSUE TITLE
30C reports being used as baro?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-8chan#84]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/5685108/225169569-0ceb67ed-4571-4fb2-978d-704607181e27.png">

**Comment by rusefillc** [comment]
Already fixed by https://github.com/rusefi/rusefi/commit/503a2bb3a562c8d76c1c43aa66562721c3bf492d

Please "popular vehicles" -> reset firmware on fresh snapshot to set baro to NONE
i guess another option is to set paro to anything explicit like AT3 and then set to NONE?
