### ISSUE TITLE
Change to USB-C

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-8chan#94]
but really once we have proper case it's Amphenol type B anyway?

i guess anything on the board should match whatever we have on Amphenol on the nice case

**Comment by ElDominio** [comment]
I think we should really use USB-C because of standarization and availability of quality cables.

**Comment by ElDominio** [comment]
I think we should really use USB-C because of standarization and availability of quality cables.

**Comment by Qwerty-OFF** [comment]
Done
