### ISSUE TITLE
Odd error when assigning injector 5?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-8chan#99]
<img width="495" alt="image" src="https://github.com/rusefi/alphax-8chan/assets/5685108/fe732efd-1a3c-49f1-aaf0-ef5abe32bac4">

But I can't see that in the full pinout?

**Comment by ElDominio** [comment]
also happens on injector 6
<img width="495" alt="image" src="https://github.com/rusefi/alphax-8chan/assets/5685108/924bc6d4-d5e2-44b8-ace0-cae712ec2bbf">

probably 7 and 8, will test if needed

**Comment by rusefillc** [comment]
@andreika-git see https://github.com/rusefi/rusefi/commit/0fb88270bce9743b02e18be4a47ea28c5adc3300 do we need to add pull-up control lines? where are those?

**Comment by rusefillc** [comment]
open question if fix breaks anything with configurable pull-ups so we need @andreika-git
